---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - crd.rru.io
  resources:
  - schedulations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.rru.io
  resources:
  - schedulations/finalizers
  verbs:
  - update
- apiGroups:
  - crd.rru.io
  resources:
  - schedulations/status
  verbs:
  - get
  - patch
  - update
